### ISSUE TITLE
submodules point to private server

### ISSUE THREAD

**Issue by petercolberg** [pdebuyl/RMPCDMD#1]
The .gitmodules file points to a private server:

```
git submodule init
```

```
Submodule 'ParseText' (git://cenoli41.ulb.ac.be/ParseText.git) registered for path 'ParseText'
Submodule 'f90h5md' (git://cenoli41.ulb.ac.be/f90h5md.git) registered for path 'f90h5md'
Submodule 'mtprng' (git://cenoli41.ulb.ac.be/mtprng.git) registered for path 'mtprng'
```

Could you change it to

```
[submodule "ParseText"]
        path = ParseText
        url = ../ParseText
[submodule "mtprng"]
        path = mtprng
        url = ../mtprng
[submodule "f90h5md"]
        path = f90h5md
        url = ../f90h5md
```

so that it works with github? The relative urls permit the use of any protocol (git, http, https).

**Comment by pdebuyl** [comment]
Fixed in 9e0b3a6

Thanks a lot for the tip, I didn't know about this! A benefit of putting the code online, I get direct feedback about the sorry state of my codebase. There are a few more issues before it builds well, as I used to require SZLIB.
