### ISSUE TITLE
Compile with -Werror on Travis

### ISSUE THREAD

**Issue by petercolberg** [pdebuyl/RMPCDMD#12]
Currently there are many warnings when compiling with gfortran 4.8 on Travis:

https://travis-ci.org/pdebuyl/RMPCDMD/builds/123596618

I suggest to compile with `-Werror` on Travis only, which turns the warnings into errors to ensure these are noticed and fixed. The tedious task of fixing the warnings is left as an exercise to the maintainer :smile:.

After all warnings have been fixed, change the appropriate line in `.travis.yml` to

```
FFLAGS=-Werror cmake ..
```

**Comment by pdebuyl** [comment]
Some warnings are not error. Consider the following issue: in H5MD element creation routines, the data variable is passed as an argument https://github.com/pdebuyl/fortran_h5md/blob/master/h5md_module.f90#L360 but for scalar variables it only serves to redirect the compiler to the proper overloaded subroutine. gfortran emits a warning for a unused variable that I couldn't find a way to fix.

**Comment by pdebuyl** [comment]
This is a common issue apparently, see https://groups.google.com/forum/#!topic/comp.lang.fortran/md06mH6RMwk

I am closing this issue.
