### ISSUE TITLE
Return non-zero exit code on errors

### ISSUE THREAD

**Issue by petercolberg** [pdebuyl/RMPCDMD#3]
Fortran 2008 adds an `error stop` statement, which prints a message to standard error and exits the program with a non-zero exit code. This is preferable to the `stop` statement that returns a zero exit code.

``` fortran
error stop "neighbour list overflow"
```

A non-zero exit code signals an error to the parent program, e.g., to immediately abort a shell script:

``` sh
#!/bin/bash
set -e -o pipefail
./RMPCDMD equilibration.config
./RMPCDMD production.config
```

**Comment by pdebuyl** [comment]
Hi Peter, thanks for the suggestion. Do you have any idea about compiler support. A bit of googling was not very conclusive on that :-/

**Comment by petercolberg** [comment]
Hi Pierre, I tested this Fortran 2008 feature with gfortran and ifort:

``` fortran
program test
  error stop "foo"
end program test
```

```
# gfortran --version
GNU Fortran (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
# gfortran -Wall -std=f2008 -O2 -o error error.f90
# ./error
ERROR STOP foo
# echo $?
1
```

```
# ifort --version
ifort (IFORT) 15.0.2 20150121
# ifort -O2 -o error error.f90
# ./error 
foo
# echo $?
128
```
